project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
base_path: config/locales
files:
  - source: /**/en.yml
    translation: /phrase-exports/%two_letters_code%.yml
