name: No outdated English keys in Phrase
on:
  pull_request:
  workflow_dispatch:

jobs:
  en-keys-to-remove:
    if: github.head_ref == 'phrase-translations'
    name: No outdated English keys in Phrase
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby and run bundle install
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run i18n-tasks
        run: bundle exec i18n-tasks missing -t diff -f keys en | bundle exec i18n-tasks tree-mv -f keys "en.{*}" "\1" > en-keys-to-remove.txt

      - name: Check that there are zero keys in other locales that don't exist in English
        run: "! test -s en-keys-to-remove.txt"

      - name: Upload list of English keys that should be removed from Phrase
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: en-keys-to-remove
          path: en-keys-to-remove.txt
